FROM docker/compose:1.26.0 AS docker-stage
FROM node:12.5-slim

COPY --from=docker-stage /usr/local/bin/docker /usr/local/bin/docker
RUN curl -sfL "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose

WORKDIR /app

CMD npm run nodemon
